[project]
name = "learning-rag"
version = "0.1.0"
description = "Learning Retrieval-Augmented Generation (RAG)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.1.0",
    "langchain-openai>=1.1.7",
]

[tool.black]
line-length = 88
target-version = ["py313"]

